### ISSUE TITLE
Include StreamFlow among CWL implementations

### ISSUE THREAD

**Issue by GlassOfWhiskey** [mr-c/cwl_methods_included#3]
The StreamFlow framework (https://streamflow.di.unito.it/) should be included among the CWL implementations. Please use the following reference to cite it:

Full Text:

```
I. Colonnelli, B. Cantalupo, I. Merelli, and M. Aldinucci, "Streamflow: cross-breeding cloud with HPC," IEEE Transactions on Emerging Topics in Computing, 2020. doi:10.1109/TETC.2020.3019202
```

BibTeX:

```
@article{streamflow:tetc,
    author = {Iacopo Colonnelli and Barbara Cantalupo and Ivan Merelli and Marco Aldinucci},
    doi = {10.1109/TETC.2020.3019202},
    journal = {{IEEE} {T}ransactions on {E}merging {T}opics in {C}omputing},
    title = {{StreamFlow}: cross-breeding cloud with {HPC}},
    year = {2020}
}
```

The main reasons why StreamFlow deserves to be listed among CWL implementations are:
 - CWL is the primary workflow language in StreamFlow. Full compatibility is still in progress, but at the moment StreamFlow only fails 5/338 conformance tests for CWL 1.2 (the latest version of the language), and the plan is to reach full support by the end of October 2021;
 - The _hybrid workflows_ methodology, of which StreamFlow is the reference implementation, enables different steps of a CWL workflow to be executed on different, potentially complex architectures, allowing users to choose the best environment for each component of their pipelines. For instance, it is possible to execute a portion of a complex workflow locally on a desktop machine, while offloading a compute bound portion to a HPC center and a data visualization part to a microservices-based application on a Kubernetes environment. StreamFlow automatically manages the deployment and life-cycle of the execution environments and all the data movements;
 - It is fully open source (https://github.com/alpha-unito/streamflow), released under the LGPLv3 license, and actively maintained and extended with new functionalities;
 - It has been already used to orchestrate CWL pipelines in the Bioinformatics [1] and Deep Learning [2,3] domains, and new use-cases in the domains of Federated Learning and Quantum Computing are in progress. Plus, it is part of several european projects: [DeepHealth](https://deephealth-project.eu/) (EC H0202 IA, ICT-2018-11, G.A. 825111) 14.8M€, [ACROSS](https://www.acrossproject.eu/) (EC H2020 IA, EuroHPC-01-2019, G.A. n. 955648) 8M€,[ADMIRE](https://www.admire-eurohpc.eu/) (EC H2020 RIA, EuroHPC-01-2019, G.A. n. 956748) 8M€, EUPEX (EC H2020 RIA, EuroHPC-02-2020, G.A. n. 101033975) 41M€, and others to come.

---

[1] I. Colonnelli, B. Cantalupo, I. Merelli, and M. Aldinucci, "Streamflow: cross-breeding cloud with HPC," IEEE Transactions on Emerging Topics in Computing, 2020. doi:10.1109/TETC.2020.3019202

[2] I. Colonnelli, B. Cantalupo, R. Esposito, M. Pennisi, C. Spampinato, and M. Aldinucci, "HPC Application Cloudification: The StreamFlow Toolkit," in 12th workshop on parallel programming and run-time management techniques for many-core architectures and 10th workshop on design tools and architectures for multicore embedded computing platforms (parma-ditam 2021), Dagstuhl, Germany, 2021, p. 5:1–5:13. doi:10.4230/OASIcs.PARMA-DITAM.2021.5

[3] I. Colonnelli, B. Cantalupo, C. Spampinato, M. Pennisi, and M. Aldinucci, "Bringing ai pipelines onto cloud-hpc: setting a baseline for accuracy of covid-19 diagnosis," in Enea cresco in the fight against covid-19, 2021. doi:10.5281/zenodo.5151511

**Comment by mr-c** [comment]
Thanks @GlassOfWhiskey ; I'll incorporate this during the next round of edits

**Comment by GlassOfWhiskey** [comment]
Hi,
Do you want me to do something here?
